name: CI

on:
  push:
    branches: 
      - main                  #bhgfbfg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create .env File
        run: |
          echo -e "ENV=golu=========================" > .env

      - name: Build and Push Docker Image
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 423755636060.dkr.ecr.us-east-2.amazonaws.com
          docker build -t golu .
          docker tag golu:latest 423755636060.dkr.ecr.us-east-2.amazonaws.com/golu:latest
          docker push 423755636060.dkr.ecr.us-east-2.amazonaws.com/golu:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set Up SSH Key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Configure AWS CLI on EC2
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: SSH into EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.145.89.175 << 'EOF'
            set -e
            sudo apt update
            sudo apt install -y awscli docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            
            echo "Docker Login"
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 423755636060.dkr.ecr.us-east-2.amazonaws.com
            docker pull 423755636060.dkr.ecr.us-east-2.amazonaws.com/golu:latest

            echo "Removing older container"
            docker rm -f golu-react-webapp || true

            echo "Running new container"
            sudo docker run -d --name golu-react-webapp -p 81:80 423755636060.dkr.ecr.us-east-2.amazonaws.com/golu:latest
            echo "✅ Deployment completed!"
          EOF
